version: '3.8'

# This docker-compose is for development only
# For production, the docker-compose.prod.yml will be defined in portainer.io

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: dnd-api
    restart: always
    environment:
        DOMAIN: localhost
        NODE_ENV: development
        SESSION_ENCRYPTION_KEY: 12345
        DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
        REDIS_PASSWORD: redis12345
        REDIS_PORT: 6379
        REDIS_HOST: dnd-redis
        API_PORT: 3000
    depends_on:
      - db
      - redis
    ports:
      - 3000
    networks:
      - default

  redis:
    container_name: dnd-redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redis12345
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - default

  db:
    container_name: dnd-postgres
    image: postgres:16.1-bullseye
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 9432:5432
    networks:
      - default

volumes:
  postgres-data:
  redis-data:
 
networks:
  default:
